# Generated by Django 5.2.4 on 2025-09-07 18:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text="e.g., '2024-2025'", max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('first_term_start', models.DateField()),
                ('first_term_end', models.DateField()),
                ('second_term_start', models.DateField()),
                ('second_term_end', models.DateField()),
                ('third_term_start', models.DateField()),
                ('third_term_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('age_range', models.CharField(blank=True, help_text="e.g., '2-3 years'", max_length=20)),
                ('is_toddler_class', models.BooleanField(default=False, help_text='Special reports for toddler classes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('general_notes', models.TextField(blank=True, help_text="General observations about the student's day")),
                ('mood_behavior', models.CharField(blank=True, help_text="Student's mood and behavior", max_length=200)),
                ('social_interaction', models.TextField(blank=True, help_text='How student interacted with peers')),
                ('potty_activities', models.TextField(blank=True, help_text='Potty training updates (for toddler classes)')),
                ('meal_notes', models.TextField(blank=True, help_text='Eating habits and meal notes')),
                ('nap_time', models.CharField(blank=True, help_text='Nap time details', max_length=100)),
                ('diaper_changes', models.IntegerField(blank=True, help_text='Number of diaper changes', null=True)),
                ('homework_completed', models.BooleanField(default=False)),
                ('homework_notes', models.TextField(blank=True)),
                ('parent_message', models.TextField(blank=True, help_text='Specific message for parents')),
                ('requires_parent_action', models.BooleanField(default=False)),
                ('parent_action_required', models.TextField(blank=True, help_text='What action parent needs to take')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_to_parent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySubSubjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_rating', models.CharField(choices=[('introduced', 'Introduced'), ('working', 'Working'), ('mastered', 'Mastered'), ('not_applicable', 'Not Applicable')], default='introduced', max_length=20)),
                ('activities_completed', models.JSONField(default=list, help_text='List of specific activities completed for this sub-subject')),
                ('learning_objectives', models.TextField(help_text='What the student was expected to learn in this sub-subject')),
                ('performance_comment', models.TextField(blank=True, help_text="Optional comment about student's performance in this sub-subject")),
                ('engagement_level', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_attention', 'Needs Attention')], default='good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sub_subject__order', 'sub_subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_description', models.TextField(help_text='Specific learning goal or objective')),
                ('complexity_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20)),
                ('expected_duration_weeks', models.PositiveIntegerField(help_text='Expected number of weeks to achieve this goal')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sub_subject__subject__name', 'sub_subject__order', 'complexity_level'],
            },
        ),
        migrations.CreateModel(
            name='ParentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('daily', 'Daily Report Feedback'), ('weekly', 'Weekly Report Feedback'), ('term', 'Term Report Feedback')], max_length=10)),
                ('feedback_text', models.TextField(help_text="Parent's feedback or questions")),
                ('parent_observations', models.TextField(blank=True, help_text="Parent's observations from home")),
                ('requests_meeting', models.BooleanField(default=False, help_text='Parent requests a meeting with teacher')),
                ('meeting_notes', models.TextField(blank=True, help_text='Notes from parent-teacher meeting')),
                ('teacher_response', models.TextField(blank=True, help_text="Teacher's response to parent feedback")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=15)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from reviewer about approval/rejection')),
                ('revision_requested', models.TextField(blank=True, help_text='Specific revisions requested')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('daily', 'Daily Report Available'), ('weekly', 'Weekly Report Available'), ('term', 'Term Report Available'), ('feedback_response', 'Teacher Responded to Feedback'), ('meeting_request', 'Meeting Requested')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_scale', models.JSONField(default=dict, help_text='JSON object defining the grading scale and boundaries')),
                ('continuous_assessment_weight', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('class_participation_weight', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_assessment_weight', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_send_daily_reports', models.BooleanField(default=False, help_text='Automatically send daily reports to parents')),
                ('require_approval_for_term_reports', models.BooleanField(default=True, help_text='Require approval before term reports are sent to parents')),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('send_sms_notifications', models.BooleanField(default=False)),
                ('daily_report_deadline_time', models.TimeField(default='16:00', help_text='Time by which daily reports should be completed')),
                ('weekly_report_deadline_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='friday', max_length=10)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Settings',
                'verbose_name_plural': 'Report Settings',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('term', 'Term Report')], max_length=10)),
                ('template_structure', models.JSONField(default=dict, help_text='JSON structure defining the report template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['template_type', 'class_level__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentLearningGoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('introduced', 'Introduced'), ('working', 'Working'), ('mastered', 'Mastered'), ('not_applicable', 'Not Applicable')], default='introduced', max_length=20)),
                ('introduced_date', models.DateField()),
                ('mastered_date', models.DateField(blank=True, null=True)),
                ('progress_notes', models.TextField(blank=True, help_text="Notes about student's progress toward this goal")),
                ('last_assessed_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student__user__first_name', 'learning_goal__sub_subject__subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], max_length=10)),
                ('total_school_days', models.IntegerField()),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('days_late', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('behavior_rating', models.CharField(choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=20)),
                ('class_teacher_comment', models.TextField(help_text="REQUIRED: Class teacher's comprehensive comment about the student's overall performance")),
                ('principal_comment', models.TextField(help_text="REQUIRED: Principal/Director's comment on the student's development")),
                ('general_strengths', models.TextField(help_text="Student's key strengths across all subjects")),
                ('general_areas_for_improvement', models.TextField(help_text='General areas that need improvement across subjects')),
                ('overall_recommendations', models.TextField(help_text='Overall recommendations for continued development')),
                ('overall_average_score', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Overall average across all subjects', max_digits=5, null=True)),
                ('overall_grade', models.CharField(blank=True, choices=[('A+', 'A+ (95-100)'), ('A', 'A (90-94)'), ('A-', 'A- (85-89)'), ('B+', 'B+ (80-84)'), ('B', 'B (75-79)'), ('B-', 'B- (70-74)'), ('C+', 'C+ (65-69)'), ('C', 'C (60-64)'), ('C-', 'C- (55-59)'), ('D+', 'D+ (50-54)'), ('D', 'D (45-49)'), ('F', 'F (0-44)')], editable=False, max_length=2)),
                ('promoted_to_next_level', models.BooleanField(default=True)),
                ('promotion_notes', models.TextField(blank=True, help_text='Notes about promotion decision if not promoted')),
                ('finalized', models.BooleanField(default=False, help_text='Once finalized, the report cannot be edited')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermSubjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuous_assessment', models.DecimalField(decimal_places=2, help_text='Continuous assessment score (40% weight)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('class_participation', models.DecimalField(decimal_places=2, help_text='Class participation score (20% weight)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_assessment', models.DecimalField(decimal_places=2, help_text='Final assessment/exam score (40% weight)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_score', models.DecimalField(decimal_places=2, editable=False, help_text='Weighted total: (CA×40% + Participation×20% + Final×40%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('letter_grade', models.CharField(choices=[('A+', 'A+ (95-100)'), ('A', 'A (90-94)'), ('A-', 'A- (85-89)'), ('B+', 'B+ (80-84)'), ('B', 'B (75-79)'), ('B-', 'B- (70-74)'), ('C+', 'C+ (65-69)'), ('C', 'C (60-64)'), ('C-', 'C- (55-59)'), ('D+', 'D+ (50-54)'), ('D', 'D (45-49)'), ('F', 'F (0-44)')], editable=False, max_length=2)),
                ('subject_teacher_comment', models.TextField(help_text="Subject teacher's comment on student's performance")),
                ('subject_strengths', models.TextField(help_text="Student's strengths in this particular subject")),
                ('areas_needing_work', models.TextField(help_text='Specific areas in this subject that need more work')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['subject__name'],
            },
        ),
        migrations.CreateModel(
            name='TermSubSubjectAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_rubric_rating', models.CharField(choices=[('introduced', 'Introduced'), ('working', 'Working'), ('mastered', 'Mastered'), ('not_applicable', 'Not Applicable')], help_text="Student's final mastery level of this sub-subject for the term", max_length=20)),
                ('progress_throughout_term', models.TextField(help_text='How the student progressed in this sub-subject throughout the term')),
                ('key_milestones_achieved', models.JSONField(default=list, help_text='Specific milestones or learning objectives achieved')),
                ('areas_for_continued_focus', models.TextField(blank=True, help_text='Areas in this sub-subject that need continued attention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sub_subject__order', 'sub_subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Addition and Subtraction', 'Reading Comprehension'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('class_levels', models.JSONField(default=list, help_text='List of class levels where this sub-subject is taught')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of teaching this sub-subject')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['subject__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.JSONField(default=list)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('weekly_summary', models.TextField(help_text="REQUIRED: Overall summary of the week's learning and development")),
                ('strengths_observed', models.TextField(help_text="REQUIRED: Student's strengths observed this week")),
                ('areas_for_improvement', models.TextField(help_text='REQUIRED: Areas that need attention and improvement')),
                ('behavioral_summary', models.TextField(help_text='REQUIRED: Summary of behavior patterns throughout the week')),
                ('academic_highlights', models.TextField(help_text='REQUIRED: Key academic achievements and progress')),
                ('homework_completion_summary', models.TextField(help_text='Summary of homework completion and quality')),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('days_late', models.IntegerField(default=0)),
                ('home_support_suggestions', models.TextField(help_text='REQUIRED: Specific suggestions for parents to support learning at home')),
                ('next_week_focus', models.TextField(help_text='REQUIRED: What to focus on in the coming week')),
                ('special_achievements', models.TextField(blank=True, help_text='Any special achievements or milestones reached this week')),
                ('concerns_or_challenges', models.TextField(blank=True, help_text='Any concerns or challenges that parents should be aware of')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySubSubjectSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_rubric_rating', models.CharField(choices=[('introduced', 'Introduced'), ('working', 'Working'), ('mastered', 'Mastered'), ('not_applicable', 'Not Applicable')], help_text='Overall assessment for this sub-subject during the week', max_length=20)),
                ('topics_activities_covered', models.JSONField(default=list, help_text='Specific topics and activities covered during the week')),
                ('weekly_progress_comment', models.TextField(help_text="REQUIRED: Detailed comment on student's progress in this sub-subject during the week")),
                ('improvement_recommendations', models.TextField(blank=True, help_text='Specific recommendations for improvement in this sub-subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sub_subject__subject__name', 'sub_subject__order'],
            },
        ),
    ]
