# Generated by Django 5.2.4 on 2025-09-07 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent_app', '0002_initial'),
        ('report_module', '0001_initial'),
        ('student_app', '0001_initial'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_attendance', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.classlevel'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports_created', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='dailysubsubjectreport',
            name='daily_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subject_reports', to='report_module.dailyreport'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.department'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='prerequisite_goals',
            field=models.ManyToManyField(blank=True, help_text='Goals that should be achieved before this one', to='report_module.learninggoal'),
        ),
        migrations.AddField(
            model_name='parentfeedback',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_feedbacks', to='report_module.dailyreport'),
        ),
        migrations.AddField(
            model_name='parentfeedback',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_feedbacks', to='parent_app.parentprofile'),
        ),
        migrations.AddField(
            model_name='parentfeedback',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_feedback_responses', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='reportapproval',
            name='daily_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='report_module.dailyreport'),
        ),
        migrations.AddField(
            model_name='reportapproval',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='reportapproval',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='reportnotification',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_module.dailyreport'),
        ),
        migrations.AddField(
            model_name='reportnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_notifications', to='parent_app.parentprofile'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='class_level',
            field=models.ForeignKey(help_text='Which class level this template is for', on_delete=django.db.models.deletion.CASCADE, to='report_module.classlevel'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studentlearninggoalprogress',
            name='learning_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='report_module.learninggoal'),
        ),
        migrations.AddField(
            model_name='studentlearninggoalprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goal_progress', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentlearninggoalprogress',
            name='tracked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_learning_goals', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='dailysubsubjectreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.subject'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='class_levels_offered', to='report_module.subject'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.classlevel'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports_as_class_teacher', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_term_reports', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='reportnotification',
            name='term_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_module.termreport'),
        ),
        migrations.AddField(
            model_name='reportapproval',
            name='term_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='report_module.termreport'),
        ),
        migrations.AddField(
            model_name='parentfeedback',
            name='term_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_feedbacks', to='report_module.termreport'),
        ),
        migrations.AddField(
            model_name='termsubjectreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.subject'),
        ),
        migrations.AddField(
            model_name='termsubjectreport',
            name='term_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reports', to='report_module.termreport'),
        ),
        migrations.AddField(
            model_name='termsubsubjectassessment',
            name='term_subject_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subject_assessments', to='report_module.termsubjectreport'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subjects', to='report_module.subject'),
        ),
        migrations.AddField(
            model_name='termsubsubjectassessment',
            name='sub_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_assessments', to='report_module.topic'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='sub_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='report_module.topic'),
        ),
        migrations.AddField(
            model_name='dailysubsubjectreport',
            name='sub_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='report_module.topic'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.classlevel'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports_created', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='reportnotification',
            name='weekly_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_module.weeklyreport'),
        ),
        migrations.AddField(
            model_name='reportapproval',
            name='weekly_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='report_module.weeklyreport'),
        ),
        migrations.AddField(
            model_name='parentfeedback',
            name='weekly_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_feedbacks', to='report_module.weeklyreport'),
        ),
        migrations.AddField(
            model_name='weeklysubsubjectsummary',
            name='sub_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='report_module.topic'),
        ),
        migrations.AddField(
            model_name='weeklysubsubjectsummary',
            name='weekly_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subject_summaries', to='report_module.weeklyreport'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='report_modu_student_fde4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='report_modu_date_d894d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['student', 'date'], name='report_modu_student_81e75b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['teacher', 'date'], name='report_modu_teacher_b0cf2c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['class_level', 'date'], name='report_modu_class_l_e7bdd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentlearninggoalprogress',
            unique_together={('student', 'learning_goal')},
        ),
        migrations.AddIndex(
            model_name='termreport',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='report_modu_student_59524d_idx'),
        ),
        migrations.AddIndex(
            model_name='termreport',
            index=models.Index(fields=['class_teacher', 'academic_year', 'term'], name='report_modu_class_t_831ffb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termreport',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='termsubjectreport',
            unique_together={('term_report', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject',)},
        ),
        migrations.AlterUniqueTogether(
            name='termsubsubjectassessment',
            unique_together={('term_subject_report', 'sub_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='dailysubsubjectreport',
            unique_together={('daily_report', 'sub_subject')},
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['student', 'week_start_date'], name='report_modu_student_c774fa_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['teacher', 'week_start_date'], name='report_modu_teacher_72eeab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('student', 'week_start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklysubsubjectsummary',
            unique_together={('weekly_report', 'sub_subject')},
        ),
    ]
