# Generated by Django 5.2.4 on 2025-08-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_module', '0001_initial'),
        ('student_app', '0001_initial'),
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.classlevel'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports_created', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='dailysubjectreport',
            name='daily_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reports', to='report_module.dailyreport'),
        ),
        migrations.AddField(
            model_name='dailysubjectreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.subject'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='class_levels_offered', to='report_module.subject'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.classlevel'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports_created', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='termsubjectreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.subject'),
        ),
        migrations.AddField(
            model_name='termsubjectreport',
            name='term_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reports', to='report_module.termreport'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.classlevel'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='student_app.studentprofile'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports_created', to='teacher_app.teacherprofile'),
        ),
        migrations.AddField(
            model_name='weeklysubjectsummary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_module.subject'),
        ),
        migrations.AddField(
            model_name='weeklysubjectsummary',
            name='weekly_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_summaries', to='report_module.weeklyreport'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='report_modu_student_fde4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='report_modu_date_d894d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['student', 'date'], name='report_modu_student_81e75b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['teacher', 'date'], name='report_modu_teacher_b0cf2c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['class_level', 'date'], name='report_modu_class_l_e7bdd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailysubjectreport',
            unique_together={('daily_report', 'subject')},
        ),
        migrations.AddIndex(
            model_name='termreport',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='report_modu_student_59524d_idx'),
        ),
        migrations.AddIndex(
            model_name='termreport',
            index=models.Index(fields=['teacher', 'academic_year', 'term'], name='report_modu_teacher_05be36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termreport',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='termsubjectreport',
            unique_together={('term_report', 'subject')},
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['student', 'week_start_date'], name='report_modu_student_c774fa_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['teacher', 'week_start_date'], name='report_modu_teacher_72eeab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('student', 'week_start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklysubjectsummary',
            unique_together={('weekly_report', 'subject')},
        ),
    ]
