# Generated by Django 5.2.4 on 2025-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_accronym',
            field=models.CharField(default='', max_length=7),
        ),
    ]
